[build]
  command = "pnpm install && pnpm run build"
  publish = "dist/spa"

[build.environment]
  NODE_VERSION = "20"       # optional, but good to match your local Node
  PNPM_HOME = "/opt/buildhome/.pnpm"
  NPM_FLAGS = "--legacy-peer-deps"

[functions]
  directory = "netlify/functions"
  external_node_modules = ["express"]
